[package]
name = "libkuiper"
version = "0.1.0"
edition = "2024"
description = "Library for the kuiper CLI tool."
authors = ["Isak Jägberg <ijagberg@protonmail.com>"]
license = "MIT"
keywords = ["postman", "integration", "requests"]
categories = ["command-line-utilities", "development-tools::testing"]
repository = "https://github.com/ijagberg/kuiper"
homepage = "https://github.com/ijagberg/kuiper"

[dependencies]
uuid = { version = "1.10.0", features = ["v4"] }
bytes = "1.10.1"
jiff = "0.1.13"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[dev-dependencies]
dotenv = "0.15.0"
test-log = "0.2.17"
