[package]
name = "kuiper"
description = "An easy-to-use HTTP integration testing tool"
version = "0.0.10"
edition = "2024"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
license = "MIT"
keywords = ["postman", "integration", "requests"]
categories = ["command-line-utilities", "development-tools::testing"]
repository = "https://github.com/ijagberg/kuiper"
homepage = "https://github.com/ijagberg/kuiper"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dotenv = "0.15.0"
pretty_env_logger = "0.5.0"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
log = "0.4.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
bytes = "1.10.1"
uuid = { version = "1.16.0", features = ["v4"] }
jiff = "0.2.13"

[dev-dependencies]
test-log = "0.2.17"
